/*
 * Copyright IBM Corp. 2017 All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package org.hyperledger.composer.bna.plugin;

import org.gradle.api.Project;

public class BNAGeneratorExtension {
	private String outputDir;
	private String description;

	public BNAGeneratorExtension(Project project) {
		outputDir = project.getName();
		description = "Business Network Archive File generated by Composer Java SDK";
	}

	public String getOutputDir() {
		return outputDir.endsWith(".bna") ? outputDir : (outputDir + ".bna");
	}

	public void setOutputDir(String outputDir) {
		this.outputDir = outputDir;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
}
